name: my-first-workflow
on: push

jobs:
  job1:
    name: JOB1
    runs-on: ubuntu-latest
    steps:
      - name: Running single command in job1
        run: echo "Hi , this is my first GitHub workflow"
      - name: checking os Release for Github hosted runner
        run: cat /etc/os-release
      - name: Calling sleep
        run: sleep 20
  job2:
     name: JOB2
     runs-on: ubuntu-latest
     steps:
       - name: checking the hostname for runner
         run: hostname
       - name: running multiple commands
         run: |
           echo " Hi from adithya"
           echo " current time is 'date' "
           sleep 20
  job3:
    name: JOB3
    needs: job1
    runs-on: ubuntu-latest
    steps:
      - name: job with single dependency
        run: sleep 10
  job4:
    name: JOB4
    needs: [job1 , job2 , job3]
    runs-on: ubuntu-latest
    steps:
      - name: job for multiple dependencys
        run: sleep 10
    
      
    
 
